### ISSUE TITLE
game upload does not work (infinite loading)

### ISSUE THREAD

**Issue by Ctrl32** [hackclub/sprig#1845]
**Describe the bug**
when clicking the "run on device button" nothing happens but it stays in the "loading state". On the Sprig hardware, the screen stays the same (the "please upload a game" text)

**To Reproduce**
[I'm using the included usb-micro cable and google chrome]
-Go to a Sprig game
-click the "run on device" button
-select the serial port of the rpi pico

**Expected behavior**
The game gets uploaded to the sprig and I can play it

**Actual behavior**  
The button never stops loading and nothing gets uploaded to the Sprig

**Screenshots**
![image](https://github.com/hackclub/sprig/assets/118561152/cce152c0-0f85-49b6-aebd-264913a98dae)
the "run on device" button never stops loading

**What I've tried:**
-redowloading and reuploading the pico-os.uf2 file
-resetting the flash memory and reuploading the pico-os.uf2 file (https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html#resetting-flash-memory)
-tried the same using microsoft edge
-tried a different game

**Comment by recursiveforte** [comment]
Thanks for submitting this issue! The fix has been committed and will be in production today.

**Comment by Ctrl32** [comment]
The issue still persists for me.
I have already tried:
-redowloading the (new?) firmware (pico-os.uf2)
-tried a different cable
-tried a different usb port

The pico seems to be fine, The arduino ide has recognized it and I've managed to run "blink" on it

**Comment by dkim19375** [comment]
Issue also occurring to me :/ (infinite loading)
