### ISSUE TITLE
Can't play games on mobile with Sprig Beta

### ISSUE THREAD

**Issue by CoolCoderSJ** [hackclub/sprig#860]
When on a phone you don't have access to the buttons and stuff to play a game.

Current editor:
![Screenshot_20230227-074153.png](https://user-images.githubusercontent.com/53063247/221566735-54b8b7ee-98ff-4889-a51d-926981483a26.png)

New editor:
![Screenshot_20230227-074214.png](https://user-images.githubusercontent.com/53063247/221566758-7bb0fbe3-23a9-40aa-8736-1ec200388e3c.png)

OS: Android 13
Browser: Kiwi (Chromium)
Device: Pixel 6a

**Comment by kognise** [comment]
Fixed!

**Comment by CoolCoderSJ** [comment]
Is it on a specific deployment url or smth cause I still can't get the buttons :(
